tests: switch to using go-cmp.Equal instead of reflect.DeepEqual
go-cmp provides convenient diffing of compound data types, for example
(for a contrived case):

=== RUN   TestParseEmailHeadersEnglishPlaintextAsciiOver7bit
    letters_test.go:32: email headers are not equal
          letters.Headers{
        - 	Date:   s"2019-04-01 07:55:00 +0100 BST",
        + 	Date:   s"2091-04-01 07:55:00 +0100 BST",
          	Sender: &{Name: "Alice Sender", Address: "alice.sender@example.com"},
          	From:   {&{Name: "Alice Sender", Address: "alice.sender@example.com"}, &{Name: "Alice Sender", Address: "alice.sender@example.net"}},
          	... // 5 identical fields
          	InReplyTo:  {"Message-Id-0@example.com"},
          	References: {"Message-Id-0@example.com"},
        - 	Subject:    "📧 Test English Pangrams",
        + 	Subject:    "Test English Pangrams",
          	Comments:   "Message Header Comment",
          	Keywords:   {"Keyword 1", "Keyword 2"},
          	... // 10 identical fields
          }
--- FAIL: TestParseEmailHeadersEnglishPlaintextAsciiOver7bit (0.00s)
FAIL
FAIL	github.com/mnako/letters	0.006s
FAIL